---
title: "Statistical learning"
author: "Jeff Goldsmith"
date: "11/26/2019"
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)
library(glmnet)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))

set.seed(1)
```


## Learning ... with statistics

Let's start with lasso.

```{r}
set.seed(11)

bwt_df = 
  read_csv("./data/birthweight.csv") %>% 
  janitor::clean_names() %>%
  mutate(
    babysex = as.factor(babysex),
    babysex = fct_recode(babysex, "male" = "1", "female" = "2"),
    frace = as.factor(frace),
    frace = fct_recode(frace, "white" = "1", "black" = "2", "asian" = "3", 
                       "puerto rican" = "4", "other" = "8"),
    malform = as.logical(malform),
    mrace = as.factor(mrace),
    mrace = fct_recode(mrace, "white" = "1", "black" = "2", "asian" = "3", 
                       "puerto rican" = "4")) %>% 
  sample_n(200)
```

to use the lasso, we'll look at `glmnet` ...

get inputs for `glmnet`

```{r}
y = bwt_df$bwt
x = model.matrix(bwt ~ ., bwt_df)[, -1]
```

fit lasso

```{r}
lambda = 10^(seq(3, -2, -0.1))

lasso_fit = 
  glmnet(x, y, lambda = lambda)

lasso_cv =
  cv.glmnet(x, y, lambda = lambda)

lambda_opt = lasso_cv$lambda.min
```

```{r}
broom::tidy(lasso_fit) %>% 
  select(term, lambda, estimate) %>% 
  complete(term, lambda, fill = list(estimate = 0) ) %>% filter(term != "(Intercept)") %>% 
  ggplot(aes(x = log(lambda, 10), y = estimate, group = term, color = term)) + 
  geom_path() + 
  geom_vline(xintercept = log(lambda_opt, 10), color = "blue", size = 1.2) +
  theme(legend.position = "none")
```

```{r}
broom::tidy(lasso_cv) %>% 
  ggplot(aes(x = log(lambda, 10), y = estimate)) + 
  geom_point()  
```





### Clustering: example 1

```{r}
poke_df = 
  read_csv("./data/pokemon.csv") %>% 
  janitor::clean_names() %>% 
  select(hp, speed)
```

```{r}
poke_df %>% 
  ggplot(aes(x = hp, y = speed)) + 
  geom_point()
```

let's cluster some things


```{r}
kmeans_fit =
  kmeans(poke_df, centers = 3)
```

process and plot results

```{r}
broom::augment(kmeans_fit, poke_df) %>% 
  ggplot(aes(x = hp, y = speed, color = .cluster)) + 
  geom_point()
```

### Clustering: trajectories


```{r}
traj_data = 
  read_csv("./data/trajectories.csv")
```

```{r}
traj_data %>% 
  ggplot(aes(x = week, y = value, group = subj)) + 
  geom_point() + 
  geom_line()
```


```{r}
int_slope_df = 
  traj_data %>% 
  nest(data = week:value) %>% 
  mutate(
    models = map(data, ~lm(value ~ week, data = .x)),
    results = map(models, broom::tidy)
  ) %>% 
  select(-data, -models) %>% 
  unnest(results) %>% 
  select(subj,term, estimate) %>% 
  pivot_wider(
    names_from = term, 
    values_from = estimate
  ) %>% 
  select(subj, int = "(Intercept)", slope = week)
```


Try to kmeans this whole thing

```{r}
km_fit = 
  kmeans(
    x = int_slope_df %>% select(-subj) %>% scale, 
    centers = 2)
```



